### ISSUE TITLE
OSLogin user is not added to all configured groups

### ISSUE THREAD

**Issue by jlucktay** [GoogleCloudPlatform/guest-agent#394]
I'm not sure if this is a documentation issue or a functionality one, so apologies if this is already covered off somewhere else.

When I create a VM with `enable-oslogin : "TRUE"` set in its metadata, and then log in to the VM, my user will not be a member of the `groups` line per the default instance config file below:

```
$ cat /etc/default/instance_configs.cfg 
[Accounts]
deprovision_remove = false
gpasswd_add_cmd = gpasswd -a {user} {group}
gpasswd_remove_cmd = gpasswd -d {user} {group}
groupadd_cmd = groupadd {group}
groups = adm,dip,docker,lxd,plugdev,video
useradd_cmd = useradd -m -s /bin/bash -p * {user}
userdel_cmd = userdel -r {user}

[Daemons]
...
```

With OS Login enabled, the only 2 groups my user ends up being a member of are (1) the one with the same name as itself, and (2) `video`. I'm not clear on why this is the case.

If I set `enable-oslogin : "FALSE"` on the VM's metadata and log in, the user who is generated that way has membership in all of those on the `groups` line in the config file above, except for `lxd`. This non-OS Login user is also a member of the `google-sudoers` group.

**Comment by a-crate** [comment]
Hi, yes this is the intended behavior. The groups configuration line is only for users created through metadata ssh keys, which is a different mechanism from oslogin that we don't support enabling at the same time. I will update the documentation to make this clearer.

OSLogin users are looked up through NSS rather than created on the local system, so being a member of the video group by default is from the OS configuration somewhere. 

Does the `lxd` group exist on that system? Are we failing to add the account to the group or does the group not exist? We don't create groups in the `groups` config line, only `google-sudoers` (this is the group used to give non-oslogin users sudo access).

**Comment by jlucktay** [comment]
OK, thank you for the notes @a-crate :)
I will circle back and double check on the `lxd` group, to see whether it already exists.
If I understand right: the name of the group (or any group) may well be set on that `groups` line, but if the group does not already exist, it will not be created. `google-sudoers` is the sole exception to this case.

**Comment by a-crate** [comment]
Yep, that is correct about groups behavior. It seems like everything is WAI then, if the documentation is still unclear or you have more questions feel free to reopen.
